### ISSUE TITLE
WechatPCAPI 异常未捕获

### ISSUE THREAD

**Issue by mortimer-cra** [Mocha-L/WechatPCAPI#3]
![](https://raw.githubusercontent.com/mortimer-cra/mypic/master/20191205105352.png)

运行一段时间后，多次出现这个错误

**Comment by Mocha-L** [comment]
@mortimer-cra 收到你的反馈了 这个问题我今晚会catch住的 打印日志输出的 后续你也可以传入log句柄 这样把日志打印出来

**Comment by Mocha-L** [comment]
@mortimer-cra 问题已经修复，请更新测试。

**Comment by YiMingFu** [comment]
ERROR:root:__compose_frind_info error catched.
Traceback (most recent call last):
  File "WechatPCAPI\WechatPCAPI.py", line 271, in WechatPCAPI.WechatPCAPI.__compose_frind_info
IndexError: list index out of range
ERROR:root:__compose_frind_info error catched.
Traceback (most recent call last):
  File "WechatPCAPI\WechatPCAPI.py", line 271, in WechatPCAPI.WechatPCAPI.__compose_frind_info
IndexError: list index out of range

**Comment by Mocha-L** [comment]
@YiMingFu 朋友你这个我记得捕获了啊 你用的是新版本的么？

**Comment by mortimer-cra** [comment]
新版跑了两天 没问题了
